AUDIO_STYLE_MEAN_VOLUME_DB = "mean_volume_db"
AUDIO_STYLE_MAX_VOLUME_DB = "max_volume_db"
AUDIO_STYLE_VOICE_PROMINENCE = "voice_prominence"
AUDIO_STYLE_ESTIMATED_STYLE = "estimated_style"
AUDIO_STYLE_HAS_SPEECH = "has_speech"
AUDIO_STYLE_MOOD = "mood"
AUDIO_STYLE_ENERGY = "energy"

AUDIO_MIX_MODE_VOICE_FIRST = "voice_first"
AUDIO_MIX_MODE_MUSIC_DRIVEN = "music_driven"
AUDIO_MIX_MODE_BALANCED = "balanced"

AUDIO_VOICE_PROMINENCE_HIGH = "high"
AUDIO_VOICE_PROMINENCE_MEDIUM = "medium"
AUDIO_VOICE_PROMINENCE_LOW = "low"

AUDIO_PLAN_MIX_MODE = "mix_mode"
AUDIO_PLAN_VOICEOVER_WEIGHT = "voiceover_weight"
AUDIO_PLAN_SOURCE_WEIGHT = "source_weight"
AUDIO_PLAN_VOICEOVER_GAIN_DB = "voiceover_gain_db"
AUDIO_PLAN_SOURCE_GAIN_DB = "source_gain_db"
AUDIO_PLAN_NORMALIZE = "normalize"
AUDIO_PLAN_REFERENCE_DRIVEN = "reference_driven"
AUDIO_PLAN_REFERENCE_AUDIO_STYLE = "reference_audio_style"

DEFAULT_VOICEOVER_WEIGHT = 0.6
DEFAULT_SOURCE_WEIGHT = 0.4
DEFAULT_VOICEOVER_GAIN_DB = 4.0
DEFAULT_SOURCE_GAIN_DB = -1.0

HIGH_VOICEOVER_WEIGHT = 0.78
HIGH_SOURCE_WEIGHT = 0.22
HIGH_VOICEOVER_GAIN_DB = 10.0
HIGH_SOURCE_GAIN_DB = -4.0

LOW_VOICEOVER_WEIGHT = 0.42
LOW_SOURCE_WEIGHT = 0.58
LOW_VOICEOVER_GAIN_DB = 0.0
LOW_SOURCE_GAIN_DB = 0.0

LOUD_MEAN_VOLUME_DB_THRESHOLD = -14.0
MEDIUM_MEAN_VOLUME_DB_THRESHOLD = -22.0
