MAX_SEARCH_ATTEMPTS_PER_SLOT = 1
MAX_PREPARE_SLOTS_PER_REQUEST = 5
MAX_DOWNLOAD_TRIES_PER_SLOT = 4

PLATFORM_SEARCH_HIT_POOL_KEY = "platform_search_hit_pool"

SLOT_STATUS_PENDING = "pending"
SLOT_STATUS_PREPARING = "preparing"
SLOT_STATUS_AWAITING_APPROVAL = "awaiting_approval"
SLOT_STATUS_APPROVED = "approved"
SLOT_STATUS_EXHAUSTED = "exhausted"
