DEMO_PACK_RECORDING = "pack_recording"
DEMO_PACK_LIVE = "pack_live"

VALID_DEMO_MODES = frozenset({DEMO_PACK_RECORDING, DEMO_PACK_LIVE})

DEMO_STEP_DELAY_SEC = 0.75
DEMO_CANDIDATE_STEP_DELAY_SEC = 1.0
DEMO_RENDER_TOTAL_SEC = 120.0

DEMO_AGENT_PLATFORM_VIDEO_SEARCH = "platform_video_search"
DEMO_AGENT_PLATFORM_VIDEO_DOWNLOAD = "platform_video_download"
DEMO_AGENT_CANDIDATE_VISUAL_ANALYSIS = "candidate_visual_analysis"
DEMO_AGENT_CANDIDATE_SEGMENT = "candidate_segment_analysis"
DEMO_AGENT_CANDIDATE_PREVIEW = "candidate_preview"

DEMO_ANALYSIS_SOURCE = "demo_replay"
