INTEGRATION_GEMINI = "gemini"
INTEGRATION_TAVILY = "tavily"
INTEGRATION_SLNG = "slng"
INTEGRATION_MUBIT = "mubit"
INTEGRATION_AIKIDO = "aikido"

INTEGRATION_STATUS_OK = "ok"
INTEGRATION_STATUS_MISSING_KEY = "missing_key"
INTEGRATION_STATUS_ERROR = "error"
INTEGRATION_STATUS_CI_ONLY = "ci_only"
INTEGRATION_STATUS_SKIPPED_DEMO = "skipped_demo"

INTEGRATION_HEALTH_CACHE_TTL_SEC = 60.0
