REFERENCE_DURATION_TOLERANCE_RATIO = 0.35
MIN_SOURCE_DURATION_SEC = 1.0
SHORT_FORM_REFERENCE_MAX_SEC = 120.0
YOUTUBE_SHORTS_MAX_DURATION_SEC = 60.0
SHORTS_SOURCE_ACCEPTANCE_MAX_SEC = 90.0

REJECTION_REASON_DURATION_TOO_LONG = "duration_too_long"
REJECTION_REASON_DURATION_TOO_SHORT = "duration_too_short"
REJECTION_REASON_WRONG_ORIENTATION = "wrong_orientation"
REJECTION_REASON_ASPECT_MISMATCH = "aspect_mismatch"
REJECTION_REASON_PROBE_FAILED = "probe_failed"

FEEDBACK_TYPE_APPROVE = "approve"
FEEDBACK_TYPE_REJECT = "reject"

VIDEO_PREFERENCES_MEMORY_KEY = "video_preferences"

PREFERENCE_DECISION_APPROVE = "approve"
PREFERENCE_DECISION_REJECT = "reject"

RANKING_ORDER_5_TO_1 = "5_to_1"
RANKING_ORDER_1_TO_5 = "1_to_5"
